<a href="https://colab.research.google.com/github/Shuvam02/AI-ML-training/blob/main/Introduction/Numpy_5th_sem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction to numpy
What we will cover?
-Creating single dimension arrays
-Multidimensional arrays
-Randomly generated arrays
-Element wise operation
-Summarizing operations

##Single Dimension Arrays

In [ ]:
import numpy as np

In [ ]:
#create an array with all the elements as 0
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
#create am array with all the elements as 1
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
#create an array of size 10 with all elements 3
np.full(10,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [ ]:
#create an array starting with 3 and ending with 9
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
#create an array with evenly spaced numbers within a specified range
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

##Multi-Dimensional Array

In [ ]:
#create 2-D array with all 0
np.a